### PR TITLE
proposed JSON format

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Comment by pikesley** [comment]
Is this a troll?

**Comment by Floppy** [comment]
That depends. It's either a troll or a serious Open Data proposal. Pick one.

**Comment by pikesley** [comment]
JSON works better for Open Data. Markdown works better for Making Better Drinks.

We need a script to render the MD from the JSON...

**Comment by Floppy** [comment]
screen in the kitchen.

OVERENGINEER ALL THE THINGS.

**Comment by pikesley** [comment]
Totally. I see my weekend disappearing into a JSON-to-Markdown rabbit hole...

**Pull request merged**
