### PR TITLE
Added DRYer yaml based format

### PR DESCRIPTION
**Pull request by mrchrisadams**
I'd like to propose this as an alternative too.

In the office we tend to have a lot of the same preferences for drinks, so using yaml keeps this a bit DRYer.

Although I don't have benchmarks, is may be slightly faster to parse, as we wouldn't be relying on RegExps so much.

### CODE REVIEW

**Comment by Floppy** [comment]
I'm not sure we want our hot drinks to be DRY.

**Comment by mrchrisadams** [comment]
Hi James, this better?

**Comment by pikesley** [comment]
Rejected because obvious trolling

**Pull request closed without merging**
